---
title: "Animals"
author: "Alejandro Alcalde"
date: "May 5, 2016"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, cache = T)
set.seed(1000000271)
```

```{r Load libraries}
set.seed(1000000271)
is.installed <- function(paquete) is.element(
  paquete, installed.packages())

if (!is.installed("dplyr"))
  install.packages("dplyr")
if (!is.installed("tidyr"))
  install.packages("tidyr")
if (!is.installed("ggplot2"))
  install.packages("ggplot2")
if (!is.installed("GGally"))
  install.packages("GGally")
if (!is.installed("lubridate"))
  install.packages("lubridate")
# if (!is.installed("VGAM"))
#   install.packages("VGAM")
if (!is.installed("gbm"))
  install.packages("gbm")
if (!is.installed("knncat"))
  install.packages("knncat")

library(dplyr)
library(ggplot2)
library(GGally)
library(lubridate)
library(tidyr)
# library(VGAM)
library(caret)
library(gbm)
library(knncat)
library(doParallel)
library(MASS)

# Todos los proyectos deben contener los siguientes apartados:
# 
# 1.- Definición del problema a resolver y enfoque elegido
# 2.- Codificación de los datos de entrada para hacerlos útiles a los algoritmos.
# 3.- Valoración del interés de la variables para el problema y selección de un subconjunto (en su caso).
# 4.- Normalización de las variables (en su caso)
# 5.- Selección de las técnica (parámetrica) y valoración de la idoneidad de la misma frente a otras alternativas
# 6.- Aplicación de la técnica especificando claramente que algoritmos se usan en la estimación de los parámetros, los hiperparámetros y el error de generalización.
# 7.- Argumentar sobre la idoneidad de la función regularización usada (en su caso)
# 8.- Valoración de los resultados ( gráficas, métricas de error, análisis de residuos, etc )
# 9.- Justificar que se ha obtenido la mejor de las posibles soluciones con la técnica elegida y la muestra dada. Argumentar en términos de la dimensión VC del modelo, el error de generalización y las curvas de aprendizaje. 
# 
# Solo son elegibles los modelos explicados en la asignatura incluyendo técnicas de reducción de dimensionalidad (PCA).
# 
# Proyectos de hasta 20 puntos
# ----------------------------
# Solo es necesario aplicar un modelo de tipo parámetrico.
# 
# 
# Proyectos de hasta 25 puntos
# ---------------------------
# Implementar, valorar y comparar al menos dos modelos uno parmétrico y otra a elegir entre (k-NN, "Función de Base Radial"). 
# 
# 
# Proyectos de hasta 30 puntos
# -----------------------------
# Implementar, valorar y comparar los resultados de un modelo paramétrico, un modelo de "Función de Base Radial" y un modelo de Red Neuronal Multicapa.
#  
```


# Proyecto hasta 20 puntos

```{r Data preprocesing}
set.seed(1000000271)
# Information dense summary of the data
data <- dplyr::tbl_df(read.csv("./data/train.csv", stringsAsFactors = F))

partitionDistribution <- function(partition) {
  print(paste('Training: ', nrow(partition$training), 'instances'))
  print(paste('Test: ', nrow(partition$test), 'instances'))
}

indexes <- caret::createDataPartition(data$OutcomeType, p = .8, list = FALSE)
partition <- list(training = data[indexes,], test = data[-indexes,])
partitionDistribution(partition)
train <- partition$training
test <- partition$test
# Show information about the data
# summary(train)

# with(train, table(AnimalType, OutcomeType))
# summary(train$OutcomeType)

# There is many animals with no value, give them a category
# apply(train, 2, function(x) sum(x == ""))

# Deal with missing values and nans
# levels(train$Name) <- c(levels(train$Name),"NoName")
# levels(train$OutcomeSubtype) <- c(levels(train$OutcomeSubtype),"Unknown")
# train$Name[train$Name == ""] <- "NoName"

dataPreprocesing <- function(data) {
  
  data$OutcomeSubtype[data$OutcomeSubtype == ""] <- "Unknown"
  data <- dplyr::filter(data, AgeuponOutcome != "")
  data <- dplyr::filter(data, SexuponOutcome != "")
  
  # summary(data)
  # No more missing values
  # apply(data, 2, function(x) sum(x == ""))
  
  data <- dplyr::select(data, -AnimalID, -DateTime)
  
  TimeValue <- sapply(data$AgeuponOutcome, 
                      function(x) strsplit(x, split = " ")[[1]][1])
  
  UnitofTime <- sapply(data$AgeuponOutcome,  
                       function(x) strsplit(x, split = " ")[[1]][2])
  
  UnitofTime <- gsub('s', '', UnitofTime)
  
  TimeValue  <- as.numeric(TimeValue)
  UnitofTime <- as.factor(UnitofTime)
  
  multiplier <- ifelse(UnitofTime == 'day', 1,
                       ifelse(UnitofTime == 'week', 7,
                              ifelse(UnitofTime == 'month', 30, 
                                     ifelse(UnitofTime == 'year', 365, NA))))
  
  # Aplicamos 
  data$AgeuponOutcome <- (TimeValue * multiplier)
  
  # Divide SexuponOutcome in three categories (Male, Female, Unknown)
  data <- tidyr::separate(dplyr::filter(data, SexuponOutcome != "Unknown"),
                          SexuponOutcome,
                          c("neutered", "sex"))
  
  data$neutered[data$neutered == "Spayed"] <- "Neutered"
  
  data$NameDummy <- ifelse(data$Name == "", 0, 1)
  data$sexDummy <- ifelse(data$sex == "Male", 0, 1)
  data$AnimalTypeDummy <- ifelse(data$AnimalType == "Cat", 0, 1)
  data$neuteredDummy <- ifelse(data$neutered == "Neutered", 0, 1)
  
  # data$isSuffering <- ifelse(data$OutcomeSubtype == "Suffering", 1, 0)
  # data$isUnknown <- ifelse(data$OutcomeSubtype == "Unknown", 1, 0)
  # data$isFoster <- ifelse(data$OutcomeSubtype == "Foster", 1, 0)
  # data$isPartner <- ifelse(data$OutcomeSubtype == "Partner", 1, 0)
  # data$isSCRP <- ifelse(data$OutcomeSubtype == "SCRP", 1, 0)
  # data$isAggressive <- ifelse(data$OutcomeSubtype == "Aggressive", 1, 0)
  # data$isOffsite <- ifelse(data$OutcomeSubtype == "Offsite", 1, 0)
  # data$isBehavior <- ifelse(data$OutcomeSubtype == "Behavior", 1, 0)
  # data$isMedical <- ifelse(data$OutcomeSubtype == "Medical", 1, 0)
  # data$isinKennel <- ifelse(data$OutcomeSubtype == "In Kennel", 1, 0)
  # data$isinFoster <- ifelse(data$OutcomeSubtype == "In Foster", 1, 0)
  # data$isRabies <- ifelse(data$OutcomeSubtype == "Rabies Risk", 1, 0)
  # data$isBarn <- ifelse(data$OutcomeSubtype == "Barn", 1, 0)
  # data$iscourt <- ifelse(data$OutcomeSubtype == "Court/Investigation", 1, 0)
  # data$isEnroute <- ifelse(data$OutcomeSubtype == "Enroute", 1, 0)
  # data$isatvet <- ifelse(data$OutcomeSubtype == "At Vet", 1, 0)
  # data$isSurgery <- ifelse(data$OutcomeSubtype == "In Surgery", 1, 0)
  
  
  # unit_Multiplier_age <- ifelse(data$AgeuponOutcome <= 185,'Infants',
  #                               ifelse(data$AgeuponOutcome > 185 & data$AgeuponOutcome<=365,'child',
  #                                      ifelse(data$AgeuponOutcome > 365 & data$AgeuponOutcome<=1085,'Adult',
  #                                             ifelse(data$AgeuponOutcome>1085,'Aged',NA))))
  # 
  # data$AgeuponOutcomeDummy <- unit_Multiplier_age
  # data$AgeuponOutcomeDummy <- ifelse(data$AgeuponOutcomeDummy == "Infants", 0,
  #                                    ifelse(data$AgeuponOutcomeDummy == "child", 1,
  #                                           ifelse(data$AgeuponOutcomeDummy == "Adult", 2,
  #                                                  ifelse(data$AgeuponOutcomeDummy == "Aged", 3, NA))))
  
  data$BreedDummy <- ifelse(grepl("Mix", data$Breed, ignore.case = T), 0, 1)

  data
}

train <- dataPreprocesing(train)
test <- dataPreprocesing(test)
dplyr::glimpse(train)
dplyr::glimpse(test)

# fit <- as.matrix(train %>% dplyr::select(AnimalTypeDummy,
#                                          neuteredDummy,
#                                          sexDummy,
#                                          # AgeuponOutcomeDummy,
#                                          # OutcomeSubtype,
#                                          NameDummy,
#                                          BreedDummy,
#                                          AgeuponOutcome,
#                                          isSuffering,
#                                           isUnknown,
#                                           isFoster ,
#                                           isPartner,
#                                           isSCRP,
#                                           isAggressive,
#                                           isOffsite,
#                                           isBehavior,
#                                           isMedical,
#                                           isinKennel,
#                                           isinFoster,
#                                           isRabies,
#                                           isBarn,
#                                           iscourt,
#                                           isEnroute,
#                                           isatvet,
#                                           isSurgery))
# 
# fit.test <- as.matrix(test %>% dplyr::select(AnimalTypeDummy,
#                                          neuteredDummy,
#                                          sexDummy,
#                                          # AgeuponOutcomeDummy,
#                                          # OutcomeSubtype,
#                                          NameDummy,
#                                          BreedDummy,
#                                          AgeuponOutcome,
#                                          isSuffering,
#                                           isUnknown,
#                                           isFoster ,
#                                           isPartner,
#                                           isSCRP,
#                                           isAggressive,
#                                           isOffsite,
#                                           isBehavior,
#                                           isMedical,
#                                           isinKennel,
#                                           isinFoster,
#                                           isRabies,
#                                           isBarn,
#                                           iscourt,
#                                           isEnroute,
#                                           isatvet,
#                                           isSurgery))
# 
# 
# doParallel::registerDoParallel(4)
# glmnet.fit.dummies <- glmnet::cv.glmnet(
#   fit,
#   as.matrix(dplyr::select(train, OutcomeType)),
#   family = "multinomial",
#   type.multinomial = "grouped",
#   parallel = T
# )
# 
# 
# prediction <- predict(glmnet.fit.dummies,
#                       newx = fit,
#                       s = "lambda.min", type = "class")
# prediction.test <- predict(glmnet.fit.dummies,
#                       newx = fit.test,
#                       s = "lambda.min", type = "class")
# 
# mean(prediction != train[,2])
# mean(prediction != test[,2])

fit <- train %>% dplyr::select(OutcomeType,
                               OutcomeSubtype,
                               AnimalTypeDummy,
                               neuteredDummy,
                               sexDummy,
                               # AgeuponOutcomeDummy,
                               NameDummy,
                               BreedDummy,
                               AgeuponOutcome)

lda.fit <- MASS::lda(OutcomeType ~ AnimalType + neutered + sex + AgeuponOutcome + NameDummy + OutcomeSubtype + BreedDummy, data = train)
lda.predict <- predict(lda.fit, train)

mean(lda.predict$class != train$OutcomeType)
```

# Proyectos hasta 25 puntos

```{r}
set.seed(1000000271)

# fit <- as.data.frame(train %>% dplyr::select(AnimalTypeDummy,
#                                          neuteredDummy,
#                                          sexDummy,
#                                          AgeuponOutcomeDummy,
#                                          NameDummy,
#                                          BreedDummy,
#                                          OutcomeType))
# 
# fit.test <- as.data.frame(test %>% dplyr::select(AnimalTypeDummy,
#                                          neuteredDummy,
#                                          sexDummy,
#                                          AgeuponOutcomeDummy,
#                                          NameDummy,
#                                          BreedDummy,
#                                          OutcomeType))

require(parallelSVM)
svm.model <- parallelSVM::parallelSVM(OutcomeType ~ ., fit, 
                        type = "C-classification",
                        kernel = "radial",
                        # degree = 6,
                        cross = 10,
                        seed = 1000000271,
                        cost = 10, scale = T)


svm.predicted <- predict(svm.model, fit.test[,-7])
table(svm.predicted, fit.test[,7])
mean(svm.predicted != fit.test[,7])*100  

```


